
/**
 *  作者：xuewq
 *  时间：2021-12-15 11:48:27
 *  描述：创建序列【SEQ_INDEX_CONTENT】
 *  脚本可重复执行
 */

PROMPT SEQ_INDEX_CONTENT  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_INDEX_CONTENT';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_INDEX_CONTENT MINVALUE 1 MAXVALUE 999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;



/**
 *  作者：xuewq
 *  时间：2021-12-15 11:48:27
 *  描述：创建表【首页展示内容管理】
 *  脚本可重复执行
 */

PROMPT T_INDEX_CONTENT 首页展示内容管理
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_INDEX_CONTENT';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_INDEX_CONTENT
			(
				MODULAR_ID  NUMBER(16) not null,
				CODE        VARCHAR2(50),
				REGION_CODE VARCHAR2(50),
				UUID        VARCHAR2(50),
				TYPE        VARCHAR2(2),
				URL         VARCHAR2(1000),
				IS_ENABLE   CHAR(1),
				REMARK      VARCHAR2(200),
				IS_VALID    CHAR(1),
				CREATOR     NUMBER(16),
				CREATE_TIME DATE,
				UPDATOR     NUMBER(16),
				UPDATE_TIME DATE,
				CONSTRAINT PK_T_INDEX_CONTENT PRIMARY KEY (MODULAR_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_INDEX_CONTENT IS ''首页展示内容管理'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.MODULAR_ID  IS ''主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.CODE  IS ''编号''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.REGION_CODE  IS ''所属区域''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.TYPE  IS ''展示类型''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.URL  IS ''链接地址''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.IS_ENABLE  IS ''是否启用''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_INDEX_CONTENT.UPDATE_TIME  IS ''修改时间''';
	END IF;
END;
/
COMMIT;




