
/**
 *  作者：王文杰
 *  时间：2021-09-14 14:58:19
 *  描述：创建序列【SEQ_T_DV_ATTRACTIONS_MANAGEMENT】
 *  脚本可重复执行
 */

PROMPT SEQ_T_DV_ATTRACTIONS_MANAGEMENT  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = SEQ_T_DV_ATTR_MANAGEMENT 
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_DV_ATTR_MANAGEMENT MINVALUE 1 MAXVALUE 99999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;





/**
 *  作者：王文杰
 *  时间：2021-09-27 16:37:54
 *  描述：创建表【景点管理表】
 *  脚本可重复执行
 */

PROMPT T_DV_ATTRACTIONS_MANAGEMENT 景点管理表
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_DV_ATTRACTIONS_MANAGEMENT';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_DV_ATTRACTIONS_MANAGEMENT
			(
				ATTRACTIONS_ID   NUMBER(16) not null,
				ATTRACTIONS_NAME VARCHAR2(100),
				ATTRACTIONS_TYPE VARCHAR2(3),
				CHARGE_TYPE      VARCHAR2(3),
				ATTRACTIONS_DESC CLOB,
				ISSU_TIME        DATE,
				UPLOAD_TIME      DATE,
				ISSU_PERSON      VARCHAR2(100),
				ISSU_ORG_NAME    VARCHAR2(100),
				ISSU_STATUS      VARCHAR2(3),
				ORG_CODE         VARCHAR2(50),
				UUID             VARCHAR2(50),
				ORG_NAME         VARCHAR2(100),
				REMARK           VARCHAR2(200),
				IS_VALID         CHAR(1) ,
				CREATOR          NUMBER(16),
				CREATE_TIME      DATE  ,
				UPDATOR          NUMBER(16),
				UPDATE_TIME      DATE ,
				ATTRACTIONS_TIME VARCHAR2(50),
				ADDRESS          VARCHAR2(100),
				PIC_URL          VARCHAR2(100),
				X                VARCHAR2(50),
				Y                VARCHAR2(50),
				CONSTRAINT PK_T_DV_ATTRACTIONS_MANAGEMENT PRIMARY KEY (ATTRACTIONS_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_DV_ATTRACTIONS_MANAGEMENT IS ''景点管理表'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ATTRACTIONS_ID  IS ''景点主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ATTRACTIONS_NAME  IS ''景点名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ATTRACTIONS_TYPE  IS ''景点类型''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.CHARGE_TYPE  IS ''收费类型''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ATTRACTIONS_DESC  IS ''景点介绍''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ISSU_TIME  IS ''发布时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.UPLOAD_TIME  IS ''上传时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ISSU_PERSON  IS ''发布人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ISSU_ORG_NAME  IS ''发布机构名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ISSU_STATUS  IS ''发布状态''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ORG_CODE  IS ''所属行政村编码''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ORG_NAME  IS ''所属行政村名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.UPDATE_TIME  IS ''修改时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ATTRACTIONS_TIME  IS ''开放时段''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.ADDRESS  IS ''景点地址''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.PIC_URL  IS ''景点主图url''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.X  IS ''经度''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ATTRACTIONS_MANAGEMENT.Y  IS ''纬度''';
	END IF;
END;
/
COMMIT;









/**
 *  作者：王文杰
 *  时间：2021-09-09 15:04:53
 *  描述：创建序列【SEQ_T_DV_RESOURCE_MANAGEMENT】
 *  脚本可重复执行
 */

PROMPT SEQ_T_DV_RESOURCE_MANAGEMENT  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_T_DV_RESOURCE_MANAGEMENT';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_DV_RESOURCE_MANAGEMENT MINVALUE 1 MAXVALUE 99999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;






/**
 *  作者：王文杰
 *  时间：2021-09-08 19:32:58
 *  描述：创建序列【SEQ_T_DV_ASSET_MANAGEMENT】
 *  脚本可重复执行
 */

PROMPT SEQ_T_DV_ASSET_MANAGEMENT  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_T_DV_ASSET_MANAGEMENT';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_DV_ASSET_MANAGEMENT MINVALUE 1 MAXVALUE 99999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;



/**
 *  作者：王文杰
 *  时间：2021-09-07 11:28:52
 *  描述：创建序列【SEQ_T_DV_FUND_MANAGEMENT】
 *  脚本可重复执行
 */

PROMPT SEQ_T_DV_FUND_MANAGEMENT  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_T_DV_FUND_MANAGEMENT';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_DV_FUND_MANAGEMENT MINVALUE 1 MAXVALUE 99999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;




/**
 *  作者：王文杰
 *  时间：11-06 10:44:11
 *  描述：创建表【资产管理表】
 *  脚本可重复执行
 */

PROMPT T_DV_ASSET_MANAGEMENT 
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_DV_ASSET_MANAGEMENT';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_DV_ASSET_MANAGEMENT
			(
				ASSET_ID         NUMBER(16) not null,
				ASSET_NAME       VARCHAR2(100),
				ASSET_TYPE       VARCHAR2(3),
				UNIT             VARCHAR2(20),
				NUMBERR          NUMBER(10),
				PURCHASE_TIME    DATE,
				STORAGE_LOCATION VARCHAR2(100),
				ASSET_VALUE      NUMBER(9,2),
				EVALUATION       NUMBER(9,2),
				USAGE            VARCHAR2(10),
				CHECK_IN_TIME    DATE,
				CHECK_IN_PERSON  VARCHAR2(100),
				OWNERSHIP        VARCHAR2(200),
				ORG_CODE         VARCHAR2(50),
				UUID             VARCHAR2(50),
				ORG_NAME         VARCHAR2(100),
				REMARK           VARCHAR2(200),
				IS_VALID         CHAR(1)  ,
				CREATOR          NUMBER(16),
				CREATE_TIME      DATE  ,
				UPDATOR          NUMBER(16),
				UPDATE_TIME      DATE  ,
				CONSTRAINT PK_T_DV_ASSET_MANAGEMENT PRIMARY KEY (ASSET_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_DV_ASSET_MANAGEMENT IS ''资产管理表'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.ASSET_ID  IS ''资产主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.ASSET_NAME  IS ''资产名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.ASSET_TYPE  IS ''资产分类''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.UNIT  IS ''单位''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.NUMBERR  IS ''数量''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.PURCHASE_TIME  IS ''购置时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.STORAGE_LOCATION  IS ''存放地点''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.ASSET_VALUE  IS ''资产价值''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.EVALUATION  IS ''评估价值''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.USAGE  IS ''使用情况''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.CHECK_IN_TIME  IS ''登记时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.CHECK_IN_PERSON  IS ''登记人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.OWNERSHIP  IS ''所有权归属''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.ORG_CODE  IS ''所属行政村编码''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.ORG_NAME  IS ''所属行政村名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_ASSET_MANAGEMENT.UPDATE_TIME  IS ''修改时间''';
	END IF;
END;
/
COMMIT;

/**
 *  作者：王文杰
 *  时间：11-06 10:44:11
 *  描述：创建表【资金管理表】
 *  脚本可重复执行
 */

PROMPT T_DV_FUND_MANAGEMENT 
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_DV_FUND_MANAGEMENT';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_DV_FUND_MANAGEMENT
			(
				ASSET_ID         NUMBER(16) not null,
				ITEM_DESCRIPTION VARCHAR2(200),
				DATE_OF_OCCUR    DATE,
				IN_AND_EX_TYPE_P VARCHAR2(20),
				IN_AND_EX_TYPE_C VARCHAR2(20),
				AMOUNT_INCURRED  NUMBER(12,2),
				ORG_CODE         VARCHAR2(50),
				UUID             VARCHAR2(50),
				ORG_NAME         VARCHAR2(100),
				REMARK           VARCHAR2(200),
				IS_VALID         CHAR(1) ,
				CREATOR          NUMBER(16),
				CREATE_TIME      DATE  ,
				UPDATOR          NUMBER(16),
				UPDATE_TIME      DATE  ,
				CONSTRAINT PK_T_DV_FUND_MANAGEMENT PRIMARY KEY (ASSET_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_DV_FUND_MANAGEMENT IS ''资金管理表'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.ASSET_ID  IS ''资金主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.ITEM_DESCRIPTION  IS ''事项说明''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.DATE_OF_OCCUR  IS ''发生日期''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.IN_AND_EX_TYPE_P  IS ''收支类型(一级)''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.IN_AND_EX_TYPE_C  IS ''收支类型(二级)''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.AMOUNT_INCURRED  IS ''发生金额''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.ORG_CODE  IS ''所属行政村编码''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.ORG_NAME  IS ''所属行政村名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FUND_MANAGEMENT.UPDATE_TIME  IS ''修改时间''';
	END IF;
END;
/
COMMIT;

/**
 *  作者：王文杰
 *  时间：11-06 10:44:11
 *  描述：创建表【资源管理表】
 *  脚本可重复执行
 */

PROMPT T_DV_RESOURCE_MANAGEMENT 
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_DV_RESOURCE_MANAGEMENT';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_DV_RESOURCE_MANAGEMENT
			(
				RESOURCE_ID         NUMBER(16) not null,
				RESOURCE_NAME       VARCHAR2(100),
				RESOURCE_TYPE       VARCHAR2(3),
				UNIT                VARCHAR2(20),
				NUMBERR             NUMBER(10),
				RESOURCE_DESC       VARCHAR2(500),
				OWNERSHIP           VARCHAR2(200),
				UTILIZATION         VARCHAR2(200),
				CONTRACTOR          VARCHAR2(100),
				CONTRACTOR_TEL      VARCHAR2(20),
				CONTRACT_PERIOD     VARCHAR2(100),
				CONTRACT_AMOUNT     NUMBER(10,2),
				CONTRACT_PAY_METHOD VARCHAR2(100),
				ORG_CODE            VARCHAR2(50),
				CHECK_IN_PERSON     VARCHAR2(100),
				CHECK_IN_TIME       DATE,
				UUID                VARCHAR2(50),
				ORG_NAME            VARCHAR2(100),
				REMARK              VARCHAR2(200),
				IS_VALID            CHAR(1) ,
				CREATOR             NUMBER(16),
				CREATE_TIME         DATE  ,
				UPDATOR             NUMBER(16),
				UPDATE_TIME         DATE  ,
				CONSTRAINT PK_T_DV_RESOURCE_MANAGEMENT PRIMARY KEY (RESOURCE_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_DV_RESOURCE_MANAGEMENT IS ''资源管理表'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.RESOURCE_ID  IS ''资源主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.RESOURCE_NAME  IS ''资源名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.RESOURCE_TYPE  IS ''资源分类''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.UNIT  IS ''单位''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.NUMBERR  IS ''数量''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.RESOURCE_DESC  IS ''资源描述''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.OWNERSHIP  IS ''所有权归属''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.UTILIZATION  IS ''利用情况''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CONTRACTOR  IS ''承包人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CONTRACTOR_TEL  IS ''承包人联系方式''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CONTRACT_PERIOD  IS ''承包期限''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CONTRACT_AMOUNT  IS ''承包金额''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CONTRACT_PAY_METHOD  IS ''承包金交纳方式''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.ORG_CODE  IS ''所属行政村编码''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CHECK_IN_PERSON  IS ''登记人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CHECK_IN_TIME  IS ''登记时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.ORG_NAME  IS ''所属行政村名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_RESOURCE_MANAGEMENT.UPDATE_TIME  IS ''修改时间''';
	END IF;
END;
/
COMMIT;




/**
 *  作者：ZHENGYI
 *  时间：2021-09-22 10:57:14
 *  描述：创建序列【SEQ_DV_CONTRACT】
 *  脚本可重复执行
 */

PROMPT SEQ_DV_CONTRACT  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_DV_CONTRACT';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_DV_CONTRACT MINVALUE 1 MAXVALUE 99999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;



/**
 *  作者：ZHENGYI
 *  时间：2021-09-22 10:57:14
 *  描述：创建表【合同管理】
 *  脚本可重复执行
 */

PROMPT T_DV_CONTRACT 合同管理
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_DV_CONTRACT';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_DV_CONTRACT
			(
				CONTRACT_ID    NUMBER(16) not null,
				UU_ID          VARCHAR2(32),
				CONTRACT_NAME  VARCHAR2(100),
				CONTRACT_AMT   NUMBER(15,2),
				PARTY_A        VARCHAR2(100),
				PARTY_B        VARCHAR2(100),
				ABSTRACT       VARCHAR2(2000),
				PAYMENT_METHOD VARCHAR2(500),
				START_TIME     DATE,
				END_TIME       DATE,
				TIME_LIMIT     VARCHAR2(6),
				REGION_CODE    VARCHAR2(32),
				REGION_NAME    VARCHAR2(100),
				IS_VALID       CHAR(1),
				CREATOR        NUMBER(16),
				CREATE_TIME    DATE,
				UPDATOR        NUMBER(16),
				UPDATE_TIME    DATE,
				REMARK         VARCHAR2(500),
				CONSTRAINT PK_T_DV_CONTRACT PRIMARY KEY (CONTRACT_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_DV_CONTRACT IS ''合同管理'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.CONTRACT_ID  IS ''主键ID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.UU_ID  IS ''唯一标识''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.CONTRACT_NAME  IS ''合同名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.CONTRACT_AMT  IS ''合同金额（元）''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.PARTY_A  IS ''甲方名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.PARTY_B  IS ''乙方名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.ABSTRACT  IS ''合同摘要''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.PAYMENT_METHOD  IS ''合同款项交纳方式''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.START_TIME  IS ''开始日期''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.END_TIME  IS ''结束日期''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.TIME_LIMIT  IS ''期限''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.REGION_CODE  IS ''所属区域''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.REGION_NAME  IS ''所属区域名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.IS_VALID  IS ''数据状态''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.UPDATOR  IS ''更新人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.UPDATE_TIME  IS ''更新时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_CONTRACT.REMARK  IS ''备注''';
	END IF;
END;
/
COMMIT;



/**
 *  作者：os.liwei
 *  时间：2021-09-24 08:47:01
 *  描述：创建序列【SEQ_T_DV_FARMHOUSE_MANAGEMENT】
 *  脚本可重复执行
 */

PROMPT SEQ_T_DV_FARMHOUSE_MANAGEMENT  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_T_DV_FARMHOUSE_MANAGEMENT';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_DV_FARMHOUSE_MANAGEMENT MINVALUE 1 MAXVALUE 99999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;



/**
 *  作者：os.liwei
 *  时间：2021-09-24 08:47:01
 *  描述：创建表【农家乐管理】
 *  脚本可重复执行
 */

PROMPT T_DV_FARMHOUSE_MANAGEMENT 农家乐管理
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_DV_FARMHOUSE_MANAGEMENT';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_DV_FARMHOUSE_MANAGEMENT
			(
				FARMHOUSE_ID      NUMBER(16) not null,
				FARMHOUSE_NAME    VARCHAR2(200),
				ADDRESS           VARCHAR2(200),
				PER_CAPITA_CONSUM VARCHAR2(200),
				OPERATOR          VARCHAR2(200),
				TEL               VARCHAR2(20),
				RELEASE_TIME      DATE,
				ISSU_TIME         DATE,
				PULISHER          VARCHAR2(100),
				ISSU_ORG_NAME     VARCHAR2(100),
				ISSU_STATUS       VARCHAR2(10),
				ORG_CODE          VARCHAR2(50),
				UUID              VARCHAR2(50),
				ORG_NAME          VARCHAR2(100),
				REMARK            VARCHAR2(200),
				IS_VALID          CHAR(1),
				CREATOR           NUMBER(16),
				CREATE_TIME       DATE,
				UPDATOR           NUMBER(16),
				UPDATE_TIME       DATE,
				SERVICE_DESC      CLOB,
				PIC_URL           VARCHAR2(200),
				CONSTRAINT PK_T_DV_FARMHOUSE_MANAGEMENT PRIMARY KEY (FARMHOUSE_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_DV_FARMHOUSE_MANAGEMENT IS ''农家乐管理'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.FARMHOUSE_ID  IS ''农家乐主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.FARMHOUSE_NAME  IS ''农家乐名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.ADDRESS  IS ''地址''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.PER_CAPITA_CONSUM  IS ''人均消费''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.OPERATOR  IS ''经营人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.TEL  IS ''联系方式''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.RELEASE_TIME  IS ''发布时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.ISSU_TIME  IS ''上传时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.PULISHER  IS ''发布人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.ISSU_ORG_NAME  IS ''发布机构名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.ISSU_STATUS  IS ''发布状态''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.ORG_CODE  IS ''所属行政村编码''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.ORG_NAME  IS ''所属行政村名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.UPDATE_TIME  IS ''修改时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.SERVICE_DESC  IS ''服务介绍''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_FARMHOUSE_MANAGEMENT.PIC_URL  IS ''标题主图''';
	END IF;
END;
/
COMMIT;




/**
 *  作者：liangxj
 *  时间：2021-12-22 10:45:25
 *  描述：创建序列【SEQ_DV_VILLAGE_GROUP】
 *  脚本可重复执行
 */

PROMPT SEQ_DV_VILLAGE_GROUP  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_DV_VILLAGE_GROUP';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_DV_VILLAGE_GROUP MINVALUE 1 MAXVALUE 999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;



/**
 *  作者：liangxj
 *  时间：2021-12-22 10:45:25
 *  描述：创建表【村小组】
 *  脚本可重复执行
 */

PROMPT T_DV_VILLAGE_GROUP 村小组
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_DV_VILLAGE_GROUP';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_DV_VILLAGE_GROUP
			(
				VILLAGE_GROUP_ID NUMBER(16) not null,
				UUID             VARCHAR2(50),
				NAME             VARCHAR2(50),
				TYPE             VARCHAR2(100),
				job             VARCHAR2(100),
				TEL              VARCHAR2(20),
				ID_NO            VARCHAR2(30),
				REGION_CODE      VARCHAR2(50),
				REGION_NAME      VARCHAR2(200),
				SEQ              NUMBER(3),
				INTRODUCTION     VARCHAR2(2000),
			    SEX                  CHAR(1),
			    BIRTHDAY             VARCHAR2(10),
				REMARK           VARCHAR2(200),
				IS_VALID         CHAR(1),
				CREATOR          NUMBER(16),
				CREATE_TIME      DATE,
				UPDATOR          NUMBER(16),
				UPDATE_TIME      DATE,
				CONSTRAINT PK_T_DV_VILLAGE_GROUP PRIMARY KEY (VILLAGE_GROUP_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_DV_VILLAGE_GROUP IS ''村小组'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.VILLAGE_GROUP_ID  IS ''主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.UUID  IS ''唯一标识''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.NAME  IS ''名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.TYPE  IS ''类型''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.job  IS ''职务''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.TEL  IS ''联系方式''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.ID_NO  IS ''身份证号''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.REGION_CODE  IS ''区域''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.REGION_NAME  IS ''区域名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.SEQ  IS ''排序''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.INTRODUCTION  IS ''人员介绍''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.UPDATE_TIME  IS ''修改时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.SEX  IS ''性别''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_DV_VILLAGE_GROUP.BIRTHDAY  IS ''出生年月''';

	END IF;
END;
/
COMMIT;




/**
 *  作者：王文杰
 *  时间：2021-12-24 15:54:19
 *  描述：创建序列【SEQ_T_VOICE_PEOPLE】
 *  脚本可重复执行
 */

PROMPT SEQ_T_VOICE_PEOPLE  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_T_VOICE_PEOPLE';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_VOICE_PEOPLE MINVALUE 1 MAXVALUE 99999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;



/**
 *  作者：王文杰
 *  时间：2021-12-24 15:54:19
 *  描述：创建表【语音人员表】
 *  脚本可重复执行
 */

PROMPT T_VOICE_PEOPLE 语音人员表
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_VOICE_PEOPLE';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_VOICE_PEOPLE
			(
				PEOPLE_ID   NUMBER(16) not null,
				NAME        VARCHAR2(50),
				SEX         CHAR(1),
				ADDRESS     VARCHAR2(200),
				TEL         VARCHAR2(50),
				PEOPLE_TYPE VARCHAR2(2),
				ORG_CODE    VARCHAR2(50),
				UUID        VARCHAR2(50),
				ORG_NAME    VARCHAR2(100),
				REMARK      VARCHAR2(200),
				IS_VALID    CHAR(1)  ,
				CREATOR     NUMBER(16),
				CREATE_TIME DATE   ,
				UPDATOR     NUMBER(16),
				UPDATE_TIME DATE   ,
				CONSTRAINT PK_T_VOICE_PEOPLE PRIMARY KEY (PEOPLE_ID)
			)';
		-- ADD COMMENTS TO THE TABLE 
		EXECUTE IMMEDIATE 'COMMENT ON TABLE T_VOICE_PEOPLE IS ''语音人员表'''; 
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.PEOPLE_ID  IS ''主键''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.NAME  IS ''名字''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.SEX  IS ''性别''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.ADDRESS  IS ''地址''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.TEL  IS ''电话''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.ORG_CODE  IS ''所属行政村编码''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.ORG_NAME  IS ''所属行政村名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_PEOPLE.UPDATE_TIME  IS ''修改时间''';
	END IF;
END;
/
COMMIT;



/**
 *  作者：王文杰
 *  时间：2021-12-27 16:41:33
 *  描述：创建序列【SEQ_T_VOICE_GROUP】
 *  脚本可重复执行
 */

PROMPT SEQ_T_VOICE_GROUP  
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_SEQUENCES ASQ
	WHERE ASQ.SEQUENCE_NAME = 'SEQ_T_VOICE_GROUP';
	IF FLAG_NUM = 0 THEN 
		EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_T_VOICE_GROUP MINVALUE 1 MAXVALUE 99999999999999999 START WITH 1 INCREMENT BY 1 CACHE 20'; 
	END IF;
END;
/
COMMIT;



/**
 *  作者：王文杰
 *  时间：2021-12-27 16:41:33
 *  描述：创建表【语音群组表】
 *  脚本可重复执行
 */

PROMPT T_VOICE_GROUP 语音群组表
DECLARE
	FLAG_NUM NUMBER;
BEGIN
	SELECT COUNT(*) INTO FLAG_NUM
	FROM USER_TABLES ATS
	WHERE ATS.TABLE_NAME = 'T_VOICE_GROUP';
	IF FLAG_NUM = 0 THEN
		EXECUTE IMMEDIATE 'CREATE TABLE T_VOICE_GROUP
			(
				GROUP_ID    NUMBER(16) not null,
				ORG_CODE    VARCHAR2(50),
				UUID        VARCHAR2(50),
				ORG_NAME    VARCHAR2(100),
				REMARK      VARCHAR2(200),
				IS_VALID    CHAR(1)  ,
				CREATOR     NUMBER(16),
				CREATE_TIME DATE    ,
				UPDATOR     NUMBER(16),
				UPDATE_TIME DATE   ,
				NAME        VARCHAR2(50),
				CONSTRAINT PK_T_VOICE_GROUP PRIMARY KEY (GROUP_ID)
			)';
		-- ADD COMMENTS TO THE COLUMNS 
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.ORG_CODE  IS ''所属行政村编码''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.UUID  IS ''UUID''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.ORG_NAME  IS ''所属行政村名称''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.REMARK  IS ''备注''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.IS_VALID  IS ''是否有效''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.CREATOR  IS ''创建人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.CREATE_TIME  IS ''创建时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.UPDATOR  IS ''修改人''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.UPDATE_TIME  IS ''修改时间''';
		EXECUTE IMMEDIATE 'COMMENT ON COLUMN T_VOICE_GROUP.NAME  IS ''名字''';
	END IF;
END;
/
COMMIT;






PROMPT 记录本次升级版本号，此段脚本放在末尾。
BEGIN 
P_SYSTEM_VERSION_LOG('01',		--01.版本升级,02:补丁升级
					'iot',	--应用程序名称
					'20201203【网格化】',--大版本号
					'v1.0.000',	--项目版本号
					'Oracle(zhsq)re_exec_table.sql'--文件名称
					);
END;
/
